export const SET_PAYMENT_TYPE = "SET_PAYMENT_TYPE";
export const SET_PAYMENT_NAME = "SET_PAYMENT_NAME";
export const SET_PAYMENT_NUMBER = "SET_PAYMENT_NUMBER";
export const SET_PAYMENT_CVV = "SET_PAYMENT_CVV";
export const SET_PAYMENT_MONTH = "SET_PAYMENT_MONTH";
export const SET_PAYMENT_YEAR = "SET_PAYMENT_YEAR";
export const SET_AVAILABILITY = "SET_AVAILABILITY";
export const SET_JOB = "SET_JOB";